# get_all_blogs
GET http://localhost:3003/api/blogs


###
# delete_a_blog
DELETE http://localhost:3003/api/blogs/64b628e180c715424dfac0b0
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMDAxIiwiaWQiOiI2NGI1Zjc5MjJlODI0MGQxN2IxMjY4Y2IiLCJpYXQiOjE2ODk2NDcxNDh9.2NxinANz54TOQvNQvgMBwDe5M9S_0RPqM4Ec357Qo9s


###
# add_a_blog
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxIiwiaWQiOiI2NGJkZWJmZmM4ZjczMzc1NWE3MzM5YjgiLCJpYXQiOjE2OTA5MzY5MTEsImV4cCI6MTY5MDk0MDUxMX0.DJ1w14QGFqf7f4i-a4XPPyUPd4bX6hDcxf7hJd4LAjY


{
    "title": "add a new blog with token012",
    "author": "aimee012",
    "url": "https://www.baidu.com",
    "likes": 15,
    "user_id": 123
}





###
# update_a_blog
# PUT http://localhost:3003/api/blogs
# content-type: application/json

# {
#    "name": "FHRFGRYEFE2",
#    "number": "00056-5466576666666"
# }


###
#add_a_comment
POST http://localhost:3003/api/blogs/64bdec00c8f733755a7339c2/comments 
Content-Type: application/json

{
"comment": "this is the first comment!"
}